//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNewsBs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public int partner_id { get; set; }
        public string partner_name { get; set; }
        public string title { get; set; }
        public string thumbnail { get; set; }
        public string description { get; set; }
    }
}
