//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebNewsBs.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int post_id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public int cate_post_id { get; set; }
        public string thumbnail { get; set; }
        public Nullable<System.DateTime> create_date { get; set; }
        public Nullable<System.DateTime> edit_date { get; set; }
        public string createby { get; set; }
        public string content { get; set; }
        public string tag { get; set; }
        public string alt { get; set; }
    
        public virtual Category_Post Category_Post { get; set; }
    }
}
